// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Log struct {
	ID        string         `json:"id"`
	Level     string         `json:"level"`
	Source    string         `json:"source"`
	Message   string         `json:"message"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt string         `json:"created_at"`
}

type Message struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
}

type Schedule struct {
	ID             string `json:"id"`
	Skill          string `json:"skill"`
	CronExpression string `json:"cron_expression"`
	Input          string `json:"input"`
	Enabled        int64  `json:"enabled"`
	CreatedAt      string `json:"created_at"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Skill struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Version     string `json:"version"`
	Location    string `json:"location"`
	Permissions string `json:"permissions"`
	Metadata    string `json:"metadata"`
	CreatedAt   string `json:"created_at"`
}

type Task struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	Skill     string         `json:"skill"`
	Input     string         `json:"input"`
	Output    sql.NullString `json:"output"`
	Status    string         `json:"status"`
	Error     sql.NullString `json:"error"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type User struct {
	ID            string `json:"id"`
	Channel       string `json:"channel"`
	ChannelUserID string `json:"channel_user_id"`
	CreatedAt     string `json:"created_at"`
}
