# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

status:
  project:
    default:
      target: auto
      threshold: 60%
      informational: false
      base: auto
      if_ci_failed: error

  patch:
    default:
      target: auto
      threshold: 60%
      informational: false
      base: auto

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/mock*.go"
  - "**/cmd/genmapper/**"
  - "**/cmd/validate-config/**"
  - "**/examples/**"
  - "**/.git/**"

github_checks:
  annotations: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false
